

<table  class="table table-striped table-bordered">   
    <thead>
        <tr>

            <th>Nome</th> 
            <th>Morada</th>
            <th>Contacto</th>
            <th>Codigo</th>
            <th>Total</th>

        </tr>
    </thead>

    <tbody>
        <?php if (isset($this->dados) && !empty($this->dados)): ?>

            <tr>
                <td><?php print $this->dados['nome']; ?></td>
                <td><?php print $this->dados['morada']; ?></td>
                <td><?php print $this->dados['telefone']; ?></td>
                <td><?php print $this->dados['codigo']; ?></td>
                <td><?php print $this->dados['total']; ?></td>
            </tr>

        <?php endif; ?>

    </tbody>
</table>

<div class="span10 " id="content" style="margin-left: 300px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-right">Descricao</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    <p><?php print $this->dados['descricao']; ?></p>


                </div>
            </div>
        </div>
    </div>
</div>



