
<div class="row-fluid" id="cliente">
    <!-- block -->
    <div class="block">
        <div class="navbar navbar-inner block-header">
            <div class="muted pull-left"><?php print $this->titulo; ?></div>
        </div>
        <div class="block-content collapse in">
            <div class="span12">
                <div class="table-toolbar">
                    <div class="btn-group">
                        <a href="<?php print URL; ?>identificacao_turnos/novo"><button class="btn btn-success" id="">Adiconar Novo <i class="icon-plus icon-white"></i></button></a>
                    </div>

                </div>

                <table  class="table table-striped table-bordered">   
                    <thead>
                        <tr>
                            <th>Turno</th>
                            <th>Inicio</th>
                            <th>Fim</th>
                            <th>Alterar</th>                            <th>Alterar</th>
                            <?php if (\application\Session::nivelViewRestrito(array('admin'))): ?>  <th>Apagar</th> <?php endif; ?> 
                        </tr>
                    </thead>

                    <tbody>
                        <?php if (isset($this->turno) && !empty($this->turno)): ?>
                            <?php foreach ($this->turno as $dados): ?>

                                <tr>
                                    <td><?php print $dados->getTurno(); ?></td>
                                    <td><?php print $dados->getInicio(); ?></td>
                                    <td><?php print $dados->getFim(); ?></td>

                                    <td><a rel="<?php print $dados->getId(); ?>" href="<?php print URL . "identificacao_turnos/editar/" . $dados->getId(); ?>" id="altera"><i class="">Alterar</i></a></td>
                                    <td><a rel="<?php $dados->getId(); ?>" href="<?php print URL . "identificacao_turnos/apagar/" . $dados->getId(); ?>" id="delete"><i class="">Apagar</i></a></td> 
                                </tr>
                            <?php endforeach; ?>

                        </tbody>
                    </table>
                <?php else: ?>
                    <h2 class="text-center alert-error">Não existe nenhuma Alarme cadastrado</h2>
                <?php endif; ?>

                <?php if (isset($this->paginacao) && !empty($this->paginacao)) echo $this->paginacao; ?>
            </div>
        </div>
    </div>
    <!-- /block -->
</div>


<hr>
