
<div class="row-fluid" id="cliente">
    <!-- block -->
    <div class="block">
        <div class="navbar navbar-inner block-header">
            <div class="muted pull-left"><?php print $this->titulo; ?></div>
        </div>
        <div class="block-content collapse in">
            <div class="span12">
                <div class="table-toolbar">
                    <div class="btn-group">
                        <a href="<?php print URL; ?>coyonet_hpas/novo"><button class="btn btn-success" id="">Adiconar Novo <i class="icon-plus icon-white"></i></button></a>
                    </div>

                </div>

                <table  class="table table-striped table-bordered">   
                    <thead>
                        <tr>

                            <th>status</th> 
                            <th>amp</th>
                            <th>power</th>
                            <th>tube_temp</th>
                            <th>Alterar</th>
                            <!-- <th>Apagar</th> --->
                            <th>Ver Usuario</th>
                        </tr>
                    </thead>

                    <tbody>
                        <?php if (isset($this->clientes) && !empty($this->clientes)): ?>
                            <?php foreach ($this->clientes as $dados): ?>

                                <tr>
                                    <td><?php print $dados['status']; ?></td>
                                    <td><?php print $dados['amp']; ?></td>
                                    <td><?php print $dados['power']; ?></td>
                                    <td><?php print $dados['tube_temp']; ?></td>
                                    
                                    <td><a rel="<?php print $dados['id']; ?>" href="<?php print URL . "alarmencc/editar/" . $dados['id']; ?>" id="altera"><i class="">Alterar</i></a></td>
                                    <!---- <td><a rel="<?php $dados['id']; ?>" href="<?php URL . "alarmencc/apagar/" . $dados['id']; ?>" id="delete"><i class="">Apagar</i></a></td>  ---->
                                    <td><a rel="<?php print $dados['id']; ?>" href="<?php print URL . "alarmencc/listar/" . $dados['id']; ?>" id="contrato"><i class="">Ver</i></a></td>
                                </tr>
                            <?php endforeach; ?>

                        </tbody>
                    </table>
                <?php else: ?>
                    <h2 class="text-center alert-error">Não existe nenhuma cliente cadastrado</h2>
                <?php endif; ?>

                <?php if (isset($this->paginacion) && !empty($this->paginacion) && (count($this->paginacion))) echo $this->paginacion; ?>

            </div>
        </div>
    </div>
    <!-- /block -->
</div>
</div>
</div>
<hr>
