
<div class="row-fluid" id="cliente">
    <!-- block -->
    <div class="block">
        <div class="navbar navbar-inner block-header">
            <div class="muted pull-left"><?php print $this->titulo; ?></div>
        </div>
        <div class="block-content collapse in">
            <div class="span12">
                <div class="table-toolbar">
                    <div class="btn-group">
                        <a href="<?php print URL; ?>coyonet_hpas/novo"><button class="btn btn-success" id="">Adiconar Novo <i class="icon-plus icon-white"></i></button></a>
                    </div>
                </div>

                <table  class="table table-striped table-bordered">   
                    <thead>
                        <tr>

                            <th>status</th> 
                            <th>amp</th>
                            <th>power</th>
                            <th>tube_temp</th>
                            <th>Observações</th>
                            <th>Alterar</th>
                            <?php if (\application\Session::nivelViewRestrito(array('admin'))): ?>  <th>Apagar</th> <?php endif; ?> 
                        </tr>
                    </thead>

                    <tbody>
                        <?php if (isset($this->coyonet) && !empty($this->coyonet)): ?>

                            <?php
                            foreach ($this->coyonet as $d):
                                ?>

                                <tr>
                                    <td><?php print $d->getStatus(); ?></td>
                                    <td><?php print $d->getAmp(); ?></td>
                                    <td><?php print $d->getPower(); ?></td>
                                    <td><?php print $d->getTubeTemp(); ?></td>
                                    <td><?php print $d->getObs(); ?></td>
                                    <td><a rel="<?php print $d->getId(); ?>" href="<?php print URL . "coyonet_hpas/editar/" . $d->getId(); ?>" id="altera"><i class="">Alterar</i></a></td>
                                    <?php if (\application\Session::nivelViewRestrito(array('admin'))): ?>   <td><a rel="<?php print $d->getId(); ?>" href="<?php print URL . "coyonet_hpas/apagar/" . $d->getId(); ?>" id="delete"><i class="">Apagar</i></a></td>
                                    <?php endif; ?>
                                </tr>
                            <?php endforeach; ?>

                        </tbody>
                    </table>
                <?php else: ?>
                    <h2 class="text-center alert-error">Não existe nenhuma cliente cadastrado</h2>
                <?php endif; ?>

                <?php if (isset($this->paginacao) && !empty($this->paginacao) && (count($this->paginacao))) echo $this->paginacao; ?>

            </div>
        </div>
    </div>
    <!-- /block -->
</div>
